### ISSUE TITLE
(CommandsFramework) ERROR: NoSuchMethodError: The getter 'bot' was called on null.

### ISSUE THREAD

**Issue by Outpox** [l7ssha/nyxx#10]
Hello! I'm having the following issue when issuing the help (with `!help`) command:
I've got 5 commands registered with the command module.
```
[SEVERE]  {Client} - 11.9.2018 19:30:30:784 -- ERROR: NoSuchMethodError: The getter 'bot' was called on null.
Receiver: null
Tried calling: bot 
 #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      new CommandsFramework.<anonymous closure>.<anonymous closure> (file:///home/outpox/.pub-cache/git/nyxx-038696e916c7d5096781ff2fdaf43c77e56076e9/lib/src/commands/CommandsFramework.dart:105:44)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#4      _DelayedData.perform (dart:async/stream_impl.dart:584:14)
#5      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#9      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#10     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#11     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

The issue is in `CommandsFramework.dart`:

```dart
_client.onReady.listen((_) {
      _client.onMessage.listen((MessageEvent e) {
        if (ignoreBots && e.message.author.bot) return; // Here
        if (!e.message.content.startsWith(prefix)) return;

        Future.microtask(() => _dispatch(e));
      });
    });
```  
This is odd because I've put a break point on the line 105 and when inspecting the `MessageEvent e` variable, `author` and `bot` are correctly set.  
  
The error also happens when messaging the bot directly (in private message).  
I'm up to date with the `development` branch.

**Comment by l7ssha** [comment]
Will look at this in few minutes. Can you tell me if message was sent by webhook? Theoretically this can be the case

**Comment by Outpox** [comment]
Mhhh I'd say no. I messaged the bot on my server in the `General` channel with `!gb_help`, `!gb_` being my prefix.  
  
```dart
main(List<String> arguments) async {
  load();  // Load dotenv
  discord.Nyxx bot = new discord.Nyxx(env["DISCORD_KEY"]);
  bot.onReady.listen((discord.ReadyEvent e) {
    print('Ready!');
  });

  command.CommandsFramework('!gb_', bot)
    ..registerLibraryCommands();
}

@command.Module("player")
class PlayerCommand extends command.CommandContext {
  @command.Command(main: true)
  @command.Help("player", usage: "!gb_player playerName")
  Future run(@command.Remainder() String argument) async {
    if (argument == "") {
      return await reply(content: "Merci de préciser un joueur");
    }
    await reply(content: 'placeholder');
  }
}
```

**Comment by l7ssha** [comment]
Yes, but at this stage of command dispatching we're filtering all messages by this `bot` property, and don't even matching prefix (this is next line).

**Comment by Outpox** [comment]
Indeed I didn't notice.
