### ISSUE TITLE
InvalidSnowflakeException when sending a sticker

### ISSUE THREAD

**Issue by arslee07** [l7ssha/nyxx#155]
**Describe the bug**
When sending a sticker, the bot throws an `InvalidSnowflakeException`.

**To Reproduce**
1. Write a minimal bot, e.x.:
```dart
import 'package:nyxx/nyxx.dart';
main() => Nyxx('<token>', GatewayIntents.allUnprivileged);
```
2. Send a sticker

**Expected behavior**
Correct sticker message parsing.

**Desktop (please complete the following information):**
 - OS: Linux
 - Dart version 2.13.4
 - Nyxx version ^2.0.0-rc.11

**Additional context**
Error message:
```
[SHOUT] [Client] Got Error: Message: [InvalidSnowflakeException: Cannot parse [{name: smiley, id: 859755587326705664, format_type: 1}] to Snowflake]. Stacktrace: 
#0      new Snowflake (package:nyxx/src/core/Snowflake.dart:29:9)
#1      new Message._new (package:nyxx/src/core/message/Message.dart:92:11)
#2      new GuildMessage._new (package:nyxx/src/core/message/Message.dart:288:58)
#3      new Message._deserialize (package:nyxx/src/core/message/Message.dart:74:27)
#4      new MessageReceivedEvent._new (package:nyxx/src/events/MessageEvents.dart:9:28)
#5      Shard._dispatch (package:nyxx/src/internal/shard/Shard.dart:310:84)
#6      Shard._handle (package:nyxx/src/internal/shard/Shard.dart:206:11)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
#11     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#12     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:475:11)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#17     _StreamController._add (dart:async/stream_controller.dart:607:7)
#18     _StreamController.add (dart:async/stream_controller.dart:554:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by HarryET** [comment]
Will look into and try to repro. Updates will be sent here 😄
