### ISSUE TITLE
NoSuchMethodError when sending embed to a DM.

### ISSUE THREAD

**Issue by One-Nub** [l7ssha/nyxx#48]
I've only seen it when sending an embed to a DM channel, regular discord channels don't have this issue. (This isn't a bot breaking bug though - the embed still shows up in the DM for the user).
Using the [rewrite_modular](https://github.com/l7ssha/nyxx/tree/rewrite_modular) branch and Dart 2.7.0.

Traceback from Logging
```
[2020-02-07 22:32:14.817696] [31m[SEVERE] [Client][0m: ERROR: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("id") 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new Message._new (package:nyxx/src/objects/message/Message.dart:98:57)
#2      new MessageUpdateEvent._new (package:nyxx/src/events/MessageEvents.dart:171:31)
#3      Shard._handleMsg (package:nyxx/src/Shard.dart:271:40)
#4      Shard._connect.<anonymous closure>.<anonymous closure> (package:nyxx/src/Shard.dart:91:18)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#7      _DelayedData.perform (dart:async/stream_impl.dart:593:14)
#8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:709:11)
#9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:669:7)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

Sample code:
```dart
@Command("dm_error")
Future<void> dmError(CommandContext ctx) async {
  DMChannel authorDM = await ctx.author.dmChannel;

  var embed = EmbedBuilder();
  embed.title = "test";

  //Both instances cause the NoSuchMethodError
  if(ctx.channel is DMChannel) {
    await ctx.message.reply(embed: embed);
  } else {
    await authorDM.send(embed: embed);
  }
}
```

**Comment by One-Nub** [comment]
It looks like the embed is registered as a message on it's own (along with a message before that also appears to contain the embed) so the raw Map given to the Message class shows up like this: 
```
{id: 246812345, embeds: [{type: rich, title: test}], channel_id: 246812345}
``` 
instead of 
```
{id: 246812345, type: 0, content: , channel_id: 246812345, author: {id: 246812345, username: 246812345, avatar: a1c5b73071b595930beac15aa62e055d, discriminator: 9277, bot: true}, attachments: [], embeds: [{type: rich, title: test}], mentions: [], mention_roles: [], pinned: false, mention_everyone: false, tts: false, timestamp: 2020-02-08T05:06:28.922000+00:00, edited_timestamp: null, flags: 0, nonce: null}
```

words are hard, so the proper map is received and then right after that the error causing map is received.
