### ISSUE TITLE
(GuildEmoji) ERROR: NoSuchMethodError: The method '[]' was called on null.

### ISSUE THREAD

**Issue by Outpox** [l7ssha/nyxx#5]
Hey there! I've faced this issue on both the `backend_rework` and the `development` branches. It doesn't happen on every server but I couldn't tell the difference. Here's the stack trace:

```
[SEVERE]  {Client} - 5.9.2018 23:45:36:204 -- ERROR: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: [](Instance of 'Snowflake') 
 #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      new GuildEmoji._new.<anonymous closure> (file:///home/outpox/.pub-cache/git/nyxx-eed68e5347a35aa1853d83a83eb83197a7cfb63d/lib/src/nyxx/objects/message/GuildEmoji.dart:41:52)
#2      List.forEach (dart:core/runtime/libgrowable_array.dart:274:8)
#3      new GuildEmoji._new (file:///home/outpox/.pub-cache/git/nyxx-eed68e5347a35aa1853d83a83eb83197a7cfb63d/lib/src/nyxx/objects/message/GuildEmoji.dart:40:20)
#4      new Guild._new.<anonymous closure> (file:///home/outpox/.pub-cache/git/nyxx-eed68e5347a35aa1853d83a83eb83197a7cfb63d/lib/src/nyxx/objects/guild/Guild.dart:111:20)
#5      List.forEach (dart:core/runtime/libgrowable_array.dart:274:8)
#6      new Guild._new (file:///home/outpox/.pub-cache/git/nyxx-eed68e5347a35aa1853d83a83eb83197a7cfb63d/lib/src/nyxx/objects/guild/Guild.dart:110:21)
#7      new GuildCreateEvent._new (file:///home/outpox/.pub-cache/git/nyxx-eed68e5347a35aa1853d83a83eb83197a7cfb63d/lib/src/nyxx/events/GuildCreateEvent.dart:10:15)
#8      Shard._handleMsg (file:///home/outpox/.pub-cache/git/nyxx-eed68e5347a35aa1853d83a83eb83197a7cfb63d/lib/src/nyxx/objects/Shard.dart:247:30)
<asynchronous suspension>
#9      Shard._connect.<anonymous closure>.<anonymous closure> (file:///home/outpox/.pub-cache/git/nyxx-eed68e5347a35aa1853d83a83eb83197a7cfb63d/lib/src/nyxx/objects/Shard.dart:77:20)
<asynchronous suspension>
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#13     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#14     _StreamController._add (dart:async/stream_controller.dart:639:7)
#15     _StreamController.add (dart:async/stream_controller.dart:585:5)
#16     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1128:21)
#17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#22     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:337:22)
#23     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#24     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#28     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#29     _StreamController._add (dart:async/stream_controller.dart:639:7)
#30     _StreamController.add (dart:async/stream_controller.dart:585:5)
#31     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#32     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#35     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#36     _StreamController._add (dart:async/stream_controller.dart:639:7)
#37     _StreamController.add (dart:async/stream_controller.dart:585:5)
#38     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1003:19)
#39     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#40     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#41     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

My `main.dart` :
```
import 'package:nyxx/nyxx.dart' as discord;
import 'package:dotenv/dotenv.dart';

main(List<String> arguments) async {
  // Load dotenv
  load();

  DoodleParser dp = DoodleParser("c6a4bi6inz4dmypa");
  await dp.loadData();

  discord.Nyxx bot = new discord.Nyxx(env["DISCORD_KEY"]);
  bot.onReady.listen((discord.ReadyEvent e) {
    print('Ready!');
  });
}
```

I believe this is because in `lib/src/nyxx/objects/message/GuildEmoji.dart` (L.41)
```
    if (raw['roles'] != null) {
      this.rolesIds = List();

      raw['roles'].forEach(
          (o) => this.rolesIds.add(this.guild.roles[Snowflake(o as String)]));
}
```

`this.guild.roles` is null. I don't know the Discord API enough to understand what could be the cause for this.

**Comment by l7ssha** [comment]
Got it, will be fixed today. Emojis are deserialized before roles in `Guild.dart` so there are problems
