### ISSUE TITLE
(GuildMemberRemoveEvent) ERROR: NoSuchMethodError: The getter 'memberCount' was called on null.

### ISSUE THREAD

**Issue by Outpox** [l7ssha/nyxx#8]
Along the error in #7 I had the following issue as well:

```
[SEVERE]  {Client} - 6.9.2018 17:8:40:409 -- ERROR: NoSuchMethodError: The getter 'memberCount' was called on null.
Receiver: null
Tried calling: memberCount 
 #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      new GuildMemberRemoveEvent._new (file:///root/.pub-cache/git/nyxx-87087a8e48300c0f24289998dcd3c66bda1142ad/lib/src/nyxx/events/GuildMemberRemoveEvent.dart:14:13)
#2      Shard._handleMsg (file:///root/.pub-cache/git/nyxx-87087a8e48300c0f24289998dcd3c66bda1142ad/lib/src/nyxx/objects/Shard.dart:274:36)
<asynchronous suspension>
#3      Shard._connect.<anonymous closure>.<anonymous closure> (file:///root/.pub-cache/git/nyxx-87087a8e48300c0f24289998dcd3c66bda1142ad/lib/src/nyxx/objects/Shard.dart:77:20)
<asynchronous suspension>
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#7      _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#8      _StreamController._add (dart:async/stream_controller.dart:639:7)
#9      _StreamController.add (dart:async/stream_controller.dart:585:5)
#10     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1128:21)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#14     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#15     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#16     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#17     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#18     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#19     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#22     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#23     _StreamController._add (dart:async/stream_controller.dart:639:7)
#24     _StreamController.add (dart:async/stream_controller.dart:585:5)
#25     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#26     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#30     _StreamController._add (dart:async/stream_controller.dart:639:7)
#31     _StreamController.add (dart:async/stream_controller.dart:585:5)
#32     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1003:19)
#33     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#34     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#35     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```  

BTW I know that this library is under development so I don't know if this issues are helpful to you, let me know ;-)

**Comment by l7ssha** [comment]
Lib isn't 100% stable yet, I'm still fixing many of bugs like that. I'll take a look at this in few minutes. Thank's for your time

**Comment by l7ssha** [comment]
I tested this and It working just fine. Dunno what causes that cache doesn't have a proper object. But I added additional null check and invalid event will be discarded.

**Comment by Outpox** [comment]
Alright awesome. Thanks for looking into it!
