### ISSUE TITLE
(User) ERROR: Invalid argument(s) 

### ISSUE THREAD

**Issue by Outpox** [l7ssha/nyxx#9]
Hello! I'm having an issue when calling `print` with a `Member` property:

```dart
// Map<Snowflake, Member> discordMembers;
this.discordMembers.forEach((id, member) => print(member));
```

`discordMembers` is retrieved from within the context of a command with `this.guild.members`.

```
[SEVERE]  {Client} - 10.9.2018 14:8:25:871 -- ERROR: Invalid argument(s) 
 #0      _StringBase._interpolate (dart:core/runtime/libstring_patch.dart:823:9)
#1      User.mention (file:///home/guillaume/.pub-cache/git/nyxx-87087a8e48300c0f24289998dcd3c66bda1142ad/lib/src/nyxx/objects/guild/User.dart:21:40)
#2      User.toString (file:///home/guillaume/.pub-cache/git/nyxx-87087a8e48300c0f24289998dcd3c66bda1142ad/lib/src/nyxx/objects/guild/User.dart:95:29)
#3      Member.toString (file:///home/guillaume/.pub-cache/git/nyxx-87087a8e48300c0f24289998dcd3c66bda1142ad/lib/src/nyxx/objects/guild/Member.dart:138:30)
#4      _StringBase._interpolateSingle (dart:core/runtime/libstring_patch.dart:799:17)
#5      print (dart:core/print.dart:9:26)
#6      new DiscordUserFromDoodle.<anonymous closure> (package:DCGB/src/DiscordUserFromDoodle.dart:14:49)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
#8      new DiscordUserFromDoodle (package:DCGB/src/DiscordUserFromDoodle.dart:14:25)
#9      DoodleParser.messageUsersOfGame.<anonymous closure> (package:DCGB/src/doodle/parser.dart:118:19)
#10     List.forEach (dart:core/runtime/libgrowable_array.dart:274:8)
#11     DoodleParser.messageUsersOfGame (package:DCGB/src/doodle/parser.dart:117:17)
#12     MPCommand.run (file:///home/guillaume/perso/projects/discord_dart/bin/main.dart:71:9)
<asynchronous suspension>
#13     _LocalInstanceMirror._invoke (dart:mirrors/runtime/libmirrors_impl.dart:327:37)
#14     _LocalInstanceMirror.invoke (dart:mirrors/runtime/libmirrors_impl.dart:323:25)
#15     CommandsFramework._dispatch (file:///home/guillaume/.pub-cache/git/nyxx-87087a8e48300c0f24289998dcd3c66bda1142ad/lib/src/commands/CommandsFramework.dart:419:28)
<asynchronous suspension>
#16     new CommandsFramework.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///home/guillaume/.pub-cache/git/nyxx-87087a8e48300c0f24289998dcd3c66bda1142ad/lib/src/commands/CommandsFramework.dart:108:32)
#17     new Future.microtask.<anonymous closure> (dart:async/future.dart:202:37)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#21     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#22     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
``` 

I believe it comes from the `mention` getter in `User.dart` L.21 with `this.id` being `null` which is weird.

**Comment by l7ssha** [comment]
It seems that members of guild aren't fully deserialized (User fields aren't filled). I'll look at this. Also are you using latest git version?

**Comment by Outpox** [comment]
By latest version you mean the `development` branch? If so, yes.  
I'll recheck my code then :-p
